spring:
  application:
    name: springcloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: d0442d84-d7d4-40dc-a3b9-eb46435f39c7
    gateway:
      routes:
        - id: springcloud-consumer
          uri: lb://springcloud-consumer
          predicates:
            - Path=/api/user/**,/api/redis/**
          filters:
            - StripPrefix=1
server:
  port: 12035