server:
  port: 12036
spring:
  application:
    name: springcloud-providerRedis
  redis:
    host: localhost
    port: 6379
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: d0442d84-d7d4-40dc-a3b9-eb46435f39c7